### PR TITLE
Chown files to a custom user after building (fix file ownership)

### LINKED ISSUE #219: Files created by the build are owned by root, not "runner"
**Bug description**

After building using the unity-builder github actions, the output files are owned by `root.root` instead of `runner.docker` like the files in git.

**How to reproduce**

Build.

**Expected behavior**

Files can be modified by the github actions

**Additional details**

The root cause here is that my build doesn't build to build/${{ targetPlatform }}/${{ targetPlatform}}.$EXTENSION, but somewhere else, and so I want to move the output around afterwards in the github workflow rather than in the build function, but I can't because of permissions. But it seems like, in general, this would be a better practice to run `chown` within the docker before finishing.

### PR DESCRIPTION
**Pull request by Bradshaw**
#### Changes

Fixes #219, without causing the issues caused by #141 

- Adds a `chownFilesTo` input
- `chown`s the files to whatever the input string is

Use it like this:
```Dockerfile
- uses: Bradshaw/unity-builder@main
  env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
      unityVersion: ${{ matrix.unityVersion }}
      targetPlatform: ${{ matrix.targetPlatform }}
      chownFilesTo: "1000:1000"
```

And it does this after building:
```sh
if [[ -n "$CHOWN_FILES_TO" ]]; then
  if [[ -n "$BUILD_PATH_FULL" ]]; then
    chown -R $CHOWN_FILES_TO $BUILD_PATH_FULL
  fi
  if [[ -n "$UNITY_PROJECT_PATH" ]]; then
    chown -R $CHOWN_FILES_TO $UNITY_PROJECT_PATH
  fi
  if [[ -n "$CUSTOM_BUILD_PATH" ]]; then
    chown -R $CHOWN_FILES_TO $CUSTOM_BUILD_PATH
  fi
fi
```

That's it... That's the fix 😅

I still think the internal Docker user should be something other than root, but that requires a heavier refactor and breaks a whole bunch of backwards-compatibility.

This is entirely optional and does absolutely nothing if the `chownFilesTo` input is unset or left blank

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme not needed
- [x] Tests not needed
- [ ] Documentation needs updating, probably

### CODE REVIEW

**Comment by webbertakken** [comment]
Just to confirm. This is an alternative solution to making the images run as a user (in a sense that one does not need the other), correct?

File: dist/steps/build.sh [hunk 1]
```diff
@@ -143,6 +143,19 @@ if [[ "$BUILD_TARGET" == "StandaloneOSX" ]]; then
...
+    chown -R $CHOWN_FILES_TO $BUILD_PATH_FULL
+  fi
+  if [[ -n "$UNITY_PROJECT_PATH" ]]; then
+    chown -R $CHOWN_FILES_TO $UNITY_PROJECT_PATH
+  fi
+  if [[ -n "$CUSTOM_BUILD_PATH" ]]; then
+    chown -R $CHOWN_FILES_TO $CUSTOM_BUILD_PATH
+  fi
+fi
+
```
Comment (webbertakken) [inline dist/steps/build.sh:158]: this can be simplified to 

```suggestion
if [[ -n "$CHOWN_FILES_TO" ]]; then
  chown -R $CHOWN_FILES_TO $BUILD_PATH_FULL
fi

```

**Comment by Bradshaw** [comment]
> Just to confirm. This is an alternative solution to making the images run as a user (in a sense that one does not need the other), correct?

Right, this is closer to a workaround than a full-on fix, and does not need any changes to be made to the images

That said, I think it's worthwhile to do anyway. When running an image as a user, it needs to be a user that has been defined in the image (AFAIK), so someone wanting to have files owned by a given user on the host machine would need to build custom images.

File: action.yml [hunk 2]
```diff
@@ -106,6 +106,10 @@ inputs:
 
       Parameters must start with a hyphen (-) and may be followed by a value (without hyphen).
       Parameters without a value will be considered booleans (with a value of true).
+  chownFilesTo:
+    required: false
+    default: ''
+    description: After building, change the ownership of the created files to this user
```
Comment (webbertakken) [inline action.yml:112]:
```suggestion
    description: 'User to give ownership of the resulting build artifacts'
```

File: dist/steps/build.sh (hunk 1 above)
Comment (Bradshaw) [reply dist/steps/build.sh:158]: The build path may be somewhere completely different to the project path, and the project path has Library and Logs directories created and owned by root, as well as the UnityBuilderAction files copied into the project 

Chowning $CUSTOM_BUILD_PATH might be redundant though indeed

Comment (webbertakken) [reply dist/steps/build.sh:158]: Right unity project path will also be needed. Editing suggestion

**Comment by webbertakken** [comment]
Will merge if you can confirm that this works :)

**Review by webbertakken — APPROVED** [review]

**Comment by Bradshaw** [comment]
The config
Screenshot 2021-05-02 at 01 13 23

The files
Screenshot 2021-05-02 at 01 13 37

The developer
thumbs
